### ISSUE TITLE
从composer拉取的代码和当前项目代码不一致

### ISSUE THREAD

**Issue by bddbnet** [jxlwqq/tencent-map#1]
[Update TencentMap.php](https://github.com/laravel-admin-extensions/tencent-map/commit/eec6027af1a11a38d1f6359ecbaa40e1ef1967ad?diff=split)

这次提交的代码没有更新到composer

**Comment by bddbnet** [comment]
当前拉取的版本 "jxlwqq/tencent-map": "^1.1",

**Comment by jxlwqq** [comment]
谢谢提醒，忘记发布了

**Comment by jxlwqq** [comment]
@bddbnet 麻烦更新到 1.1.1 版本哈
